pipeline {
    agent any
   
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps { 
                  retry(3) {
                    bat 'echo "Deploying"'
                }
                timeout(time: 3, unit: 'SECONDS') {
                    bat 'ping -n 10 127.0.0.1'
                }
            
            }
        }
    }
}
